### PR TITLE
create Github GC site

### PR DESCRIPTION
**Pull request by rleir**
Just a suggestion, if you like we can add this line.

### CODE REVIEW

**Comment by obrien-j** [comment]
Thanks for the suggestion @rleir 

I wouldn't recommend wording it the way you had as managing the entire GC under a single organization would likely be a nightmare without some assistance.... but I think we (CDS-SNC) might be interested in working with @Acasovan and @smellems to get something like https://code.gov setup for the GC.... I was thinking something along the lines of https://code.canada.ca setup.

I'm personally not a huge fan of putting all eggs into Github (no offence awesome people at Github), when there are always 'reasons' for people to use other services.

**Comment by rleir** [comment]
@obrien-j You definitely should reword it, I do not understand all the issues. 
And if some groups prefer Apache, LinuxFoundation, or others instead of github, I would welcome the sentiment.
We have some people here at Statcan who would probably jump at the chance to join in and host within CDS-SNC's github space. And what about WET-BOEW? CKAN? I suppose there could be a problem in that most projects aspire to be world-wide, and a GC-focussed space might not be appropriate.

**Comment by obrien-j** [comment]
https://government.github.com/community/  <-- If you search for canada, you'll see quite a few government linked organization's already.. I would assume there are more, but that might not have officially tied themselves to a gov organization. We should probably take this offline, but feel free to reach out to me john.obrien@cds-snc.ca

**Comment by gcharest** [comment]
Please note that the Open Resource Exchange pilot/prototype has been setup under the following [repo](https://canada-ca.github.io/ore-ero/home.html).

**Pull request closed without merging**
